# Producción

En esta etapa se preparará el modelo seleccionado para su utilización en un entorno productivo.

Para ello se guardará el modelo entrenado, se construirá un pipeline de inferencia y se desarrollará una API utilizando FastAPI.

Posteriormente, la aplicación será containerizada mediante Docker y desplegada en la nube utilizando AWS.

El objetivo final es disponer de un servicio capaz de recibir nuevas transacciones y predecir automáticamente si presentan riesgo de fraude.

## Guardado del Modelo

Una vez seleccionado Random Forest como modelo final, se procede a almacenarlo en disco para permitir su reutilización sin necesidad de volver a entrenarlo.

Esto facilitará su integración posterior dentro del pipeline de producción y de la API de predicción.

In [2]:
import joblib

In [3]:
%run 04_modeling.ipynb

(283726, 30)
(283726,)
X_train: (226980, 30)
X_test: (56746, 30)
y_train: (226980,)
y_test: (56746,)
Original
Class
0    0.998333
1    0.001667
Name: proportion, dtype: float64

Train
Class
0    0.998335
1    0.001665
Name: proportion, dtype: float64

Test
Class
0    0.998326
1    0.001674
Name: proportion, dtype: float64
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56651
           1       0.85      0.58      0.69        95

    accuracy                           1.00     56746
   macro avg       0.92      0.79      0.84     56746
weighted avg       1.00      1.00      1.00     56746

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56651
           1       0.97      0.73      0.83        95

    accuracy                           1.00     56746
   macro avg       0.99      0.86      0.92     56746
weighted avg       1.00      1.00      1.00     56746

Requirement already satisfied: xgboost in c:\Users\Asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.3.0)
Requirement already satisfied: numpy in c:\Users\Asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from xgboost) (2.4.1)
Requirement already satisfied: scipy in c:\Users\Asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from xgboost) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56651
           1       0.75      0.69      0.72        95

    accuracy                           1.00     56746
   macro avg       0.87      0.85      0.86     56746
weighted avg       1.00      1.00      1.00     56746

In [4]:
joblib.dump(modelo_rf, "modelo_fraude.pkl")

['modelo_fraude.pkl']

In [5]:
import os

os.listdir()

['01_eda.ipynb',
 '02_cleaning.ipynb',
 '03_feature_engineering.ipynb',
 '04_modeling.ipynb',
 '05_evaluation.ipynb',
 '06_production.ipynb',
 'modelo_fraude.pkl']

## Carga del Modelo

Una vez almacenado el modelo entrenado, es importante verificar que puede cargarse correctamente desde disco.

Esto permite reutilizar el modelo en aplicaciones de producción sin necesidad de repetir el proceso de entrenamiento.

In [6]:
modelo_cargado = joblib.load("modelo_fraude.pkl")

## Validación del Modelo Cargado

Una vez cargado el modelo desde disco, se verifica que continúe funcionando correctamente realizando predicciones sobre el conjunto de prueba.

Esta validación garantiza que el proceso de serialización y carga del modelo no afectó su comportamiento.

In [7]:
predicciones = modelo_cargado.predict(X_test)

predicciones[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Pipeline

En un entorno productivo, las transformaciones aplicadas a los datos y el modelo de Machine Learning deben ejecutarse siempre en el mismo orden.

Para garantizar la consistencia del proceso de inferencia, se construirá un Pipeline que integre las etapas necesarias antes de generar una predicción.

In [8]:
from sklearn.pipeline import Pipeline

In [9]:
pipeline = Pipeline([
    ("modelo", modelo_cargado)
])

In [10]:
pipeline

Pipeline(steps=[('modelo', RandomForestClassifier(random_state=42))])

## FastAPI

Para exponer el modelo como un servicio accesible desde aplicaciones externas, se utilizará FastAPI.

La API permitirá recibir nuevas transacciones mediante peticiones HTTP y devolver una predicción indicando si existe riesgo de fraude.

In [11]:
%pip install fastapi uvicorn

Requirement already satisfied: fastapi in c:\Users\Asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (0.138.0)
Requirement already satisfied: uvicorn in c:\Users\Asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (0.49.0)
Requirement already satisfied: starlette>=0.46.0 in c:\Users\Asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from fastapi) (1.3.1)
Requirement already satisfied: pydantic>=2.9.0 in c:\Users\Asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from fastapi) (2.13.4)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\Users\Asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from fastapi) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\Users\Asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from fastapi) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\Users\Asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from fastapi) (0.0.4)
Requirement already satisfied: click>=7.0 in c:\Users\Asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from uvicorn) (8.4.1)
Requirement already satisfied: h11>=0.8 in c:\Users\Asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from uvicorn) (0.16.0)
Requirement already satisfied: colorama in C:\Users\Asus\AppData\Roaming\Python\Python314\site-packages (from click>=7.0->uvicorn) (0.4.6)
Requirement already satisfied: annotated-types>=0.6.0 in c:\Users\Asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pydantic>=2.9.0->fastapi) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\Users\Asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pydantic>=2.9.0->fastapi) (2.46.4)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\Users\Asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from starlette>=0.46.0->fastapi) (4.13.0)
Requirement already satisfied: idna>=2.8 in c:\Users\Asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (3.18)
Note: you may need to restart the kernel to use updated packages.

In [20]:
import fastapi

## Creación de la API

Se crea una API utilizando FastAPI para exponer el modelo de detección de fraude.

La API permitirá recibir información de una transacción y devolver una predicción indicando si la operación presenta riesgo de fraude.

In [ ]:
from fastapi import FastAPI

app = FastAPI()

from pydantic import BaseModel

class Transaction(BaseModel):
    Time: float
    V1: float
    V2: float
    V3: float
    V4: float
    V5: float
    V6: float
    V7: float
    V8: float
    V9: float
    V10: float
    V11: float
    V12: float
    V13: float
    V14: float
    V15: float
    V16: float
    V17: float
    V18: float
    V19: float
    V20: float
    V21: float
    V22: float
    V23: float
    V24: float
    V25: float
    V26: float
    V27: float
    V28: float
    Amount_scaled: float

In [12]:
@app.get("/")
def home():
    return {"mensaje": "API de detección de fraude funcionando"}

In [14]:
@app.post("/predict")
def predict(transaction: Transaction):
    datos = pd.DataFrame([transaction.model_dump()])
    prediccion = modelo_cargado.predict(datos)
    return {"resultado": int(prediccion[0])}

In [15]:
X_test.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28',
       'Amount_scaled'],
      dtype='str')

In [16]:
import pandas as pd

In [17]:
ejemplo = X_test.iloc[[0]]

ejemplo

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount_scaled
86568,61290.0,1.228821,-0.063408,0.274145,0.647465,-0.048135,0.372073,-0.224231,0.079939,0.640759,...,-0.096566,-0.129554,-0.083779,-0.151661,-0.700372,0.59855,0.491409,0.002989,0.001782,-0.146016

In [18]:
modelo_cargado.predict(ejemplo)

array([0])

In [19]:
import json

ejemplo = X_test.iloc[0].to_dict()

with open("../sample_request.json", "w") as f:
    json.dump(ejemplo, f, indent=4)

In [23]:
X_test[y_test == 1].head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount_scaled
116139,74159.0,-1.548788,1.808698,-0.953509,2.213085,-2.015728,-0.913457,-2.356013,1.197169,-1.678374,...,0.390786,0.855138,0.774745,0.059037,0.343200,-0.468938,-0.278338,0.625922,0.395573,0.764011
95597,65385.0,-2.923827,1.524837,-3.018758,3.289291,-5.755542,2.218276,-0.509995,-3.569444,-1.016592,...,-0.447039,-0.511657,-0.122724,-4.288639,0.563797,-0.949451,-0.204532,1.510206,-0.324706,18.526631
240222,150494.0,1.852889,1.069593,-1.776101,4.617410,0.770413,-0.400859,-0.040970,0.089510,-0.217705,...,-0.288392,-0.157869,-0.176244,0.027437,-0.468006,0.058063,0.148263,0.042278,0.040573,-0.292032
203700,134928.0,1.204934,3.238070,-6.010324,5.720847,1.548400,-2.321064,-0.781880,0.076619,-2.976249,...,0.338161,0.098341,-0.845866,-0.031228,0.421146,0.388361,0.056035,0.491828,0.340847,-0.305938
249239,154309.0,-0.082983,-3.935919,-2.616709,0.163310,-1.400952,-0.809419,1.501580,-0.471000,1.519743,...,1.878612,0.702672,-0.182305,-0.921017,0.111635,-0.071622,-1.125881,-0.170947,0.126221,14.949103

In [24]:
import json

ejemplo_fraude = X_test[y_test == 1].iloc[0].to_dict()

with open("../sample_request_fraud.json", "w") as f:
    json.dump(ejemplo_fraude, f, indent=4)